#19: Use PyObject_HEAD_INIT(NULL) as per Python c-api docs.
  - https://docs.python.org/2/c-api/typeobj.html#c.PyObject.ob_type
  - This also made obsolete some previous #defs
  - This is because Python plugin would not compile on Windows
    error: initializer element is not constant (neduard/#5).