avoid "assignment within conditional expression" and handle -L for the
2005-03-06  Hans Breuer  <hans@breuer.org>

	* app/app_procs.c : avoid "assignment within conditional expression"
	and handle -L for the GOption case as well.

	* lib/widget.c : strchr() does not return -1 on not found but NULL;
	avoids widgets.c(307) : error C4047: '!=' : 'char *' differs in levels of
	indirection from 'const int '

	* lib/diasvgenderer.c(draw_arc|fill_arc) : finally correct sweep and
	large_arc, thus produce correct arc output (like diasvg.py does;),
	fixes bug #144401

	* lib/dia_svg.[hc](dia_svg_parse_path) : new function copied and adapted
	from objects/custom/shape_info.c to be shared with object/custom and
	plug-in/svg -> finally the C based svg-import reads pathes again.
	Added arc parsing while I was there, which fixes bug #169191
	* objects/custom/shape_info.c(parse_path) :
	* plug-ins/svg/svg-import : reuse above function
	Also fix the "root element was 'svg' -- expecting 'svg'" bug #108502.
	But in general this does only support a small subset of what is
	possible in SVG.