Add C++ guards, to make wmf plug-in link on win32
This is a fix for the fix:

Commit:15dd90da6635d5d8d36546f6a0524f6c03c30179
* Newer gcc chokes on cascaded extern "C"
error: template with C linkage ...
(cherry picked from commit feeefe286b7aa9184c78241fc43a10453b8397bd)